[information]
name = 'onedarker'
background = 'dark'
author = 'Johan Palacios <johanpalacios.rivera@gmail.com>'

[palette]
fg = '#ABB2BF'
bg = '#23272e'
alt_fg = '#9CA5B4'
alt_bg = '#21252A'
red = '#E06C75'
darkred = '#be5046'
green = '#98c379'
vibrant_green = '#7eca9c'
yellow = '#E5C07B'
darkyellow = '#d19a66'
sun = '#EBCB8B'
blue = '#61afef'
purple = '#C678DD'
dark_purple = '#c882e7'
baby_pink = '#DE8C92'
pink = '#ff75a0'
line = '#31353d'
cyan = '#56b6c2'
teal = '#519ABA'
white = '#abb2bf'
black = '#23272e'
foreground = '#ABB2BF'
background = '#23272e'
comment_grey = '#5C6370'
buffer_grey = '#5c6370'
gutter_fg_grey = '#4B5263'
cursor_grey = '#2C323C'
visual_grey = '#3E4452'
menu_grey = '#3E4452'
special_grey = '#3b4048'
vertsplit = '#3E4452'
lightyellow = '#e5c07b'
magenta = '#c678dd'
guttergrey = '#4b5263'
grayillum = '#3E4452'
graylens = '#4e545f'
graydep = '#808080'
contrast ="#1e2227"

# Git
sign_add = '#98c379'
sign_change = '#e5c07b'
sign_delete = '#e06c75'

# Telescope
telescope_prev = '#282c34'

# Lsp
error = '#be5046'
warn = '#e5c07b'
info = '#1cbc9b'
hint = '#4bc1fe'
error_bg = '#31262d'
warn_bg = '#32302f'
info_bg = '#1e3135'
hint_bg = '#22323f'
reference = '#2e303b'

#UI
ui_blue = '#264F78'
ui2_blue = '#042E48'
ui3_blue = '#0195F7'
ui4_blue = '#75BEFF'
ui5_blue = '#083C5A'
ui_orange = '#E8AB53'
ui2_orange = '#613214'
ui_purple = '#B180D7'
visual = '#42566f'

# Tab
tab = '#373b43'

# Folder
folder = '#61afef'


[highlights]
Normal = 'fg bg'
SignColumn = '- -'
# MsgArea = 'fg bg'
ModeMsg = '- -'
MsgSeparator = 'link:StatusLine'
SpellBad = 'red - u'
SpellCap = 'darkyellow - u'
SpellLocal = 'darkyellow - u'
SpellRare = 'darkyellow - u'
# NormalNC = 'fg bg'
Pmenu = 'white black'
PmenuSel = 'black blue'
WildMenu = 'black blue'
Cursor = 'bg fg'
CursorLineNr = 'fg - b'
Comment = 'comment_grey - i'
Folded = 'comment_grey'
FoldColumn = '-'
VertSplit = 'vertsplit'
NonText = 'special_grey'
LineNr = 'gutter_fg_grey -'
WinSeparator = 'link:VertSplit'
FloatBorder = 'link:WinSeparator'
Whitespace = 'link:NonText'
CursorLine = '- #2C313C'
CursorColumn = '- alt_bg'
ColorColumn = '- cursor_grey'
NormalFloat = '- black'
Visual = '- visual_grey'
VisualNOS = '- visual_grey'
WarningMsg = 'yellow'
DiffAdd = 'green black'
DiffChange = 'yellow - u'
DiffDelete = 'black red'
DiffText = 'black yellow'
QuickFixLine = 'black yellow'
PmenuSbar = '- cursor_grey'
PmenuThumb = '- white'
MatchWord = 'blue - u'
MatchParen = 'blue - u'
MatchWordCur = '- - u'
MatchParenCur = '- - u'
lCursor = 'bg fg'
CursorIM = 'bg fg'
TermCursor = 'bg fg'
TermCursorNC = 'bg fg'
jonceal = '-'
Directory = 'blue'
SpecialKey = 'special_grey - b'
Title = 'green - b'
ErrorMsg = 'red'
Search = 'bg green'
IncSearch = 'link:Search'
Substitute = 'link:Search'
MoreMsg = '- -'
Question = 'purple'
EndOfBuffer = 'black'
Variable = 'yellow'
String = 'green'
Character = 'green'
Constant = 'red'
Number = 'darkyellow'
Boolean = 'darkyellow'
Float = 'darkyellow'
FloatTitle = 'fg bg'
Identifier = 'red'
Function = 'blue'
Operator = 'purple'
Type = 'yellow'
StorageClass = 'yellow'
Structure = 'darkyellow'
Typedef = 'darkyellow'
Keyword = 'purple'
Statement = 'purple'
Conditional = 'purple'
Repeat = 'purple'
Label = 'purple'
Exception = 'link:Keyword'
Include = 'blue'
PreProc = 'yellow'
Define = 'purple'
Macro = 'purple'
PreCondit = 'yellow'
Special = 'blue'
SpecialChar = 'darkyellow'
Conceal = 'white -'
Tag = '- -'
Debug = '- -'
Delimiter = '- -'
SpecialComment = 'comment_grey'
Underlined = '- - u'
Bold = '- - b'
Italic = '- - i'
Ignore = 'cyan bg b'
Todo = 'purple'
Error = 'red'
TabLine = 'comment_grey'
TabLineSel = 'white'
TabLineFill = '- alt_bg'
healthError = 'red'
healthSuccess = 'green'
healthWarning = 'yellow'

[Treesitter]
'@none' = '- -'
'@preproc' = 'link:PreProc'
'@comment' = 'link:Comment'
'@annotation' = 'link:PreProc'
'@identifier' = 'red'
'@attribute' = 'link:PreProc'
'@constructor' = 'red'
'@type' = 'link:Type'
'@type.builtin' = 'link:Typedef'
'@type.definition' = 'link:@type'
'@type.qualifier' = 'link:@type'
'@conditional' = 'link:Conditional'
'@exception' = 'link:Exception'
'@include' = 'link:Include'
'@operator' = 'link:Operator'
'@keyword' = 'link:Keyword'
'@keyword.function' = 'link:Keyword'
'@keyword.operatior' = 'link:@operator'
'@keyword.return' = 'link:@keyword'
'@label' = 'link:Label'
'@namespace' = 'link:StorageClass'
'@repeat' = 'link:Repeat'
'@constant' = 'link:Constant'
'@constant.builtin' = 'link:Special'
'@constant.macro' = 'link:Define'
'@float' = 'link:Float'
'@number' = 'link:Number'
'@boolean' = 'link:Boolean'
'@character' = 'link:Character'
'@character.special' = 'link:SpecialChar'
'@error' = 'link:Error'
'@function' = 'link:Function'
'@function.builtin' = 'link:Special'
'@function.call' = 'link:@function'
'@function.macro' = 'link:Macro'
'@method' = 'link:@function'
'@method.call' = 'link:@method'
'@property' = 'link:Identifier'
'@field' = 'link:Identifier'
'@parameter' = 'link:Identifier'
'@parameter.reference' = 'link:@parameter'
'@symbol' = 'link:Identifier'
'@storageclass' = 'link:StorageClass'
'@text' = 'link:@none'
'@text.danger' = 'link:WarningMsg'
'@text.warning' = 'link:Todo'
'@text.strong' = 'fg - b'
'@text.emphasis' = 'fg - i'
'@text.underline' = 'fg - u'
'@text.strike' = 'fg - s'
'@text.title' = 'fg - b'
'@text.literal' = 'link:@String'
'@text.uri' = 'cyan - u'
'@text.note' = 'link:SpecialComment'
'@text.math' = 'fg'
'@text.reference' = 'link:Constant'
'@text.enviroment' = 'fg'
'@text.enviroment.name' = 'fg'
'@text.diff.add' = 'link:SignAdd'
'@text.diff.delete' = 'link:SignDelete'
'@text.literal.markdown' = 'blue'
'@text.literal.markdown_inline' = 'blue'
'@punctuation.delimiter' = 'link:Delimiter'
'@punctuation.bracket' = 'white'
'@punctuation.special' = 'purple'
'@punctuation.special.markdown' = 'darkyellow - b'
'@tag' = 'red'
'@tag.delimiter' = 'white'
'@tag.attribute' = 'darkyellow'
'@string' = 'link:String'
'@string.reguex' = 'link:SpecialChar'
'@string.escape' = 'link:SpecialChar'
'@string.special' = 'link:SpecialChar'
'@variable' = 'link:Variable'
'@variable.builtin' = 'link:Special'


[XML]
xmlAttrib = 'darkyellow'
xmlEndTag = 'red'
xmlTag = 'red'
xmlTagName = 'red'

[Whichkey]
WhichKeyBorder = 'graylens -'

[Telescope]
TelescopeBorder = 'bg bg'
TelescopeNormal = 'bg'
TelescopePreviewBorder = 'telescope_prev telescope_prev'
TelescopePreviewNormal = 'fg telescope_prev'
TelescopePreviewTitle = 'bg green'
TelescopePromptBorder = 'black black'
TelescopePromptNormal = 'white black'
TelescopePromptPrefix = 'red black'
TelescopePromptTitle = 'bg red'
TelescopeResultsBorder = 'telescope_prev telescope_prev'
TelescopeResultsNormal = '- telescope_prev'
TelescopeResultsTitle = 'telescope_prev telescope_prev'

[Git]
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'link:SignAdd'
GitSignsChange = 'link:SignChange'
GitSignsDelete = 'link:SignDelete'

[LSP]
DiagnosticHint = 'hint'
DiagnosticInfo = 'info'
DiagnosticWarn = 'warn'
DiagnosticError = 'error'
DiagnosticOther = 'purple'
DiagnosticSignHint = 'link:DiagnosticHint'
DiagnosticSignInfo = 'link:DiagnosticInfo'
DiagnosticSignWarn = 'link:DiagnosticWarn'
DiagnosticSignError = 'link:DiagnosticError'
DiagnosticSignOther = 'link:DiagnosticOther'
DiagnosticSignWarning = 'link:DiagnosticWarn'
DiagnosticFloatingHint = 'link:DiagnosticHint'
DiagnosticFloatingInfo = 'link:DiagnosticInfo'
DiagnosticFloatingWarn = 'link:DiagnosticWarn'
DiagnosticFloatingError = 'link:DiagnosticError'
DiagnosticUnderlineHint = '- - c hint'
DiagnosticUnderlineInfo = '- - c info'
DiagnosticUnderlineWarn = '- - c warn'
DiagnosticUnderlineError = '- - c error'
DiagnosticSignInformation = 'link:DiagnosticInfo'
DiagnosticVirtualTextHint = 'hint hint_bg'
DiagnosticVirtualTextInfo = 'info info_bg'
DiagnosticVirtualTextWarn = 'warn warn_bg'
DiagnosticVirtualTextError = 'error error_bg'

LspDiagnosticsError = 'error'
LspDiagnosticsWarning = 'warn'
LspDiagnosticsInfo = 'info'
LspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsHint = 'hint'
LspDiagnosticsDefaultError = 'link:LspDiagnosticsError'
LspDiagnosticsDefaultWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsDefaultInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultHint = 'link:LspDiagnosticsHint'
LspDiagnosticsVirtualTextError = 'link:DiagnosticVirtualTextError'
LspDiagnosticsVirtualTextWarning = 'link:DiagnosticVirtualTextWarn'
LspDiagnosticsVirtualTextInformation = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextInfo = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextHint = 'link:DiagnosticVirtualTextHint'
LspDiagnosticsFloatingError = 'link:LspDiagnosticsError'
LspDiagnosticsFloatingWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsFloatingInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingHint = 'link:LspDiagnosticsHint'
LspDiagnosticsSignError = 'link:LspDiagnosticsError'
LspDiagnosticsSignWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsSignInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignHint = 'link:LspDiagnosticsHint'

NvimTreeLspDiagnosticsError = 'link:LspDiagnosticsError'
NvimTreeLspDiagnosticsWarning = 'link:LspDiagnosticsWarning'
NvimTreeLspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsInfo = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsHint = 'link:LspDiagnosticsHint'

LspDiagnosticsUnderlineError = 'link:DiagnosticUnderlineError'
LspDiagnosticsUnderlineWarning = 'link:DiagnosticUnderlineWarn'
LspDiagnosticsUnderlineInformation = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineInfo = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineHint = 'link:DiagnosticUnderlineHint'

LspReferenceRead = '- reference'
LspReferenceText = '- reference'
LspReferenceWrite = '- reference'

LspCodeLens = 'graylens - i'
LspCodeLensSeparator = 'graylens - i'
LspInlayHint = "graylens alt_bg i"

# Semantic tockens

'@lsp.type.comment' = 'link:Comment'
'@lsp.type.enum' = 'link:Type'
'@lsp.type.interface' = 'link:@identifier'
'@lsp.type.keyword' = 'link:@keyword'
'@lsp.type.namespace' = 'link:@namespace'
'@lsp.type.parameter' = 'link:@parameter'
'@lsp.type.property' = 'link:@property'
'@lsp.type.variable' = 'link:@variable'
'@lsp.typemod.method.defaultLibrary' = 'link:@function.builtin'
'@lsp.typemod.function.defaultLibrary' = 'link:@function.builtin'
'@lsp.typemod.variable.defaultLibrary' = 'link:@variable.builtin'
'@lsp.typemod.operator.injected' = 'link:@operator'
'@lsp.typemod.string.injected' = 'link:@string'
'@lsp.typemod.variable.injected' = 'link:@variable'

[Illuminate]
IlluminatedWordWrite = '- menu_grey'
IlluminatedWordRead = '- menu_grey'
IlluminatedWordText = '- menu_grey'

[NvimTree]
NvimTreeFolderIcon = 'link:Directory'
NvimTreeNormalFloat = '- contrast'
NvimTreeIndentMarker = 'alt_fg'
NvimTreeNormal = 'fg contrast'
NvimTreeWinSeparator = 'contrast contrast'
NvimTreeEndOfBuffer = 'contrast contrast'
NvimTreeFolderName = 'link:Directory'
NvimTreeOpenedFolderName = 'folder - bi'
NvimTreeEmptyFolderName = 'comment_grey - i'
NvimTreeGitIgnored = 'comment_grey - i'
NvimTreeImageFile = 'magenta'
NvimTreeSpecialFile = 'darkyellow'
NvimTreeCursorLine = '- #2C313A'
NvimTreeGitStaged = 'sign_add'
NvimTreeGitNew = 'sign_add'
NvimTreeGitRenamed = 'sign_add'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'sign_change'
NvimTreeGitDirty = 'sign_change'
NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'fg - b'
NvimTreeExecFile = 'green'

[Buffer]
# BarBar
BufferCurrent = 'fg bg'
BufferCurrentIndex = 'fg bg'
BufferCurrentMod = 'yellow bg'
BufferCurrentSign = 'fg bg'
BufferCurrentTarget = 'red bg b'

BufferVisible = 'fg alt_bg'
BufferVisibleIndex = 'fg alt_bg'
BufferVisibleMod = 'yellow alt_bg'
BufferVisibleSign = 'fg alt_bg'
BufferVisibleTarget = 'red alt_bg b'

BufferInactive = 'comment_grey alt_bg'
BufferInactiveIndex = 'comment_grey alt_bg'
BufferInactiveMod = '#a58354 alt_bg'
BufferInactiveSign = '- alt_bg'
BufferInactiveTarget = 'red alt_bg b'

BufferTabpage = 'visual alt_bg'
BufferTabpages = '- alt_bg'

# BufferLine
BufferLineBackground = 'comment_grey alt_bg'
BufferLineIndicatorVisible = 'alt_bg alt_bg'
BufferLineBuffer = 'fg bg'
BufferLineBufferVisible = 'comment_grey alt_bg'
BufferLineCloseButton = 'comment_grey alt_bg'
BufferLineCloseButtonVisible = 'comment_grey alt_bg'
BufferLineSeparator = 'alt_bg alt_bg'
BufferLineSeparatorSelected = 'link:BufferLineSeparator'
BufferLineSeparatorVisible = 'link:BufferLineSeparator'
BufferLineGroupLabel = 'alt_bg alt_bg'
BufferLineOffsetSeparator = 'alt_bg alt_bg'
BufferLineGroupSeparator = 'bg bg'
BufferLineIndicatorSelected = 'bg bg'
BufferLineCloseButtonSelected = 'red bg'
BufferLineFill = 'fg alt_bg'
BufferLineModified = 'green -'
BufferLineModifiedSelected = 'link:BufferLineModified'
BufferLineModifiedVisible = 'red -'
BufferLineDevIconDefault = 'red -'
BufferLineDevIconDefaultSelected = 'red -'
BufferLineDevIconDefaultInactive = 'red -'
BufferLineTab = 'fg bg'
BufferLineTabSelected = 'bg #81a1c1'
BufferLineTabSeparator = 'bg bg'
BufferLineTabSeparatorSelected = 'link:BufferLineTabSelected'
BufferLineTabClose = 'red bg'

[StatusLine]
StatusLine = 'white black'
StatusLineNC = 'black black'
StatusLineSeparator = 'black'
StatusLineTerm = 'black'
StatusLineTermNC = 'black'

[IndentBlankline]
IndentBlanklineContextChar = 'purple'
IndentBlanklineChar = '#3b4048'
IndentBlanklineSpaceCharBlankline = 'darkyellow'
IndentBlanklineContextStart = '- - u'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[Cmp]
CmpItemAbbr = 'fg'
CmpItemAbbrMatchFuzzy = 'blue'
CmpItemAbbrDeprecated = 'comment_grey - s'
CmpItemKindFunction = 'purple'
CmpItemKindMethod = 'blue'
CmpItemKindConstructor = 'cyan'
CmpItemKindClass = 'yellow'
CmpItemKindEnum = 'cyan'
CmpItemKindEvent = 'yellow'
CmpItemKindInterface = 'cyan'
CmpItemKindStruct = 'cyan'
CmpItemKindVariable = 'blue'
CmpItemKindField = 'red'
CmpItemKindProperty = 'red'
CmpItemKindEnumMember = 'darkyellow'
CmpItemKindConstant = 'darkyellow'
CmpItemKindKeyword = 'darkyellow'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'fg'
CmpItemKindUnit = 'fg'
CmpItemKindText = 'fg'
CmpItemKindSnippet = 'purple'
CmpItemKindFile = 'fg'
CmpItemKindFolder = 'fg'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'fg'
CmpItemKindOperator = 'fg'
CmpItemKindTypeParameter = 'red'

[LspSaga]
TitleString = 'white black'
TitleSymbol = 'black black'
TitleIcon = 'red black'
SagaBorder = 'link:FloatBorder'
SagaNormal = 'link:Normal'
SagaExpand = 'red'
SagaCollapse = 'red'
SagaBeacon = 'magenta'
ActionPreviewTitle = 'purple black'
CodeActionText = 'yellow'
CodeActionConceal = 'green'
FinderSelection = 'cyan - b'
FinderFileName = 'white'
FinderIcon = 'cyan'
FinderType = 'purple'
FinderSpinnerTitle = 'magenta - b'
FInderVirtText = 'red'
RenameNormal = 'darkyellow black'
CallHierarchyIcon = 'purple'
CallHierarchyTitle = 'red'
SagaShadow = '- black'
OutlineIndent = 'link:IndentBlanklineContextChar'


[TSRainbowDelimiter]
RainbowDelimiterRed = 'red'
RainbowDelimiterYellow = 'yellow'
RainbowDelimiterBlue = 'blue'
RainbowDelimiterOrange = 'darkyellow'
RainbowDelimiterGreen = 'green'
RainbowDelimiterViolet = 'purple'
RainbowDelimiterCyan = 'cyan'


[Trouble]
TroubleText = 'green'
TroubleCount = 'purple guttergrey'

[Diff]
DiffAdd = 'green'
DiffDelete = 'red'
DiffText = 'green'
DiffChange = 'link:Visual'


[Fidget]
FidgetTitle = 'green -'
FidgetTask = 'special_grey -'

[Navic]
NavicIconsFile = 'fg'
NavicIconsModule = 'cyan'
NavicIconsNamespace = 'fg'
NavicIconsPackage = 'fg'
NavicIconsClass = 'yellow'
NavicIconsMethod = 'blue'
NavicIconsProperty = 'red'
NavicIconsField = 'red'
NavicIconsConstructor = 'cyan'
NavicIconsEnum = 'cyan'
NavicIconsInterface = 'cyan'
NavicIconsFunction = 'purple'
NavicIconsVariable = 'blue'
NavicIconsConstant = 'darkyellow'
NavicIconsString = 'green'
NavicIconsNumber = 'darkyellow'
NavicIconsBoolean = 'darkyellow'
NavicIconsArray = 'cyan'
NavicIconsObject = 'cyan'
NavicIconsKey = 'purple'
NavicIconsKeyword = 'darkyellow'
NavicIconsNull = 'darkyellow'
NavicIconsEnumMember = 'darkyellow'
NavicIconsStruct = 'cyan'
NavicIconsEvent = 'yellow'
NavicIconsOperator = 'fg'
NavicIconsTypeParameter = 'red'
NavicText = 'white'
NavicSeparator = 'white'


[Notify]
NotifyERRORBorder = '#8A1F1F'
NotifyWARNBorder = '#79491D'
NotifyINFOBorder = 'ui_blue'
NotifyDEBUGBorder = 'comment_grey'
NotifyTRACEBorder = '#4F3552'
NotifyERRORIcon = 'error'
NotifyWARNIcon = 'warn'
NotifyINFOIcon = 'ui4_blue'
NotifyDEBUGIcon = 'comment_grey'
NotifyTRACEIcon = 'ui_purple'
NotifyERRORTitle = 'error'
NotifyWARNTitle = 'warn'
NotifyINFOTitle = 'ui4_blue'
NotifyDEBUGTitle = 'comment_grey'
NotifyTRACETitle = 'ui_purple'

[Lazy]
LazyButton = 'fg bg'
LazyButtonActive = 'fg comment_grey'
LazyComment = 'link:Comment'
LazyCommit = 'darkyellow'
LazyCommitIssue = 'blue'
LazyH1 = 'blue bg b'
LazyReasonStart = 'cyan'
LazySpecial = 'blue'
LazyUrl = 'blue'
LazyValue = 'cyan'

[DevIcon]
DevIconjs = 'yellow'
DevIconDefault = 'red'

[Dap]
DapBreakpoint = 'red'
DapBreakpointCondition = 'yellow'
DapLogPoint = 'cyan'
DapStopped = 'purple'
DapUIScope = 'cyan'
DapUIType = 'purple'
DapUIValue = 'cyan'
DapUIVariable = 'white'
DapUIModifiedValue = 'darkyellow'
DapUIDecoration = 'cyan'
DapUIThread = 'green'
DapUIStoppedThread = 'green'
DapUISource = 'blue'
DapUILineNumber = 'cyan'
DapUIFloatBorder = 'cyan'
DapUIWatchesEmpty = 'purple'
DapUIWatchesValue = 'green'
DapUIWatchesError = 'purple'
DapUIBreakpointsPath = 'cyan'
DapUIBreakpointsInfo = 'green'
DapUIBreakPointsCurrentLine = 'green - b'
DapUIBreakpointsDisabledLine = 'comment_grey'
DapUIStepOver = 'blue'
DapUIStepInto = 'blue'
DapUIStepBack = 'blue'
DapUIStepOut = 'blue'
DapUIStop = 'red'
DapUIPlayPause = 'green'
DapUIRestart = 'green'
DapUIUnavailable = 'comment_grey'


# Languaje

[java]
#LspTokens
'@lsp.type.class.java' = 'yellow'
'@lsp.type.parameter.java' = 'red'
'@lsp.type.variable.java' = 'red'
'@lsp.type.interface.java' = 'yellow'
'@lsp.mod.constructor.java' = 'blue'
#Treesiter
'@include.java' = 'purple'
'@boolean.java' = 'darkyellow'
'@type.qualifier.java' = 'purple'
'@parameter.java' = 'red'
'@type.java' = 'yellow'
'@variable.java' = 'red'
'@variable.builtin.java' = 'yellow'
'@function.builtin.java' = 'yellow'
'@type.builtin.java' = 'purple'

[javascript]
'@variable.builtin.javascript' = 'yellow'

[lua]
'@constant.lua' = 'yellow'
'@variable.builtin.lua' = 'yellow'
#LspTokens
'@lsp.typemod.variable.defaultLibrary.lua' = 'yellow'
'@lsp.type.parameter.lua' = 'yellow'
'@lsp.type.function.lua' = '-'
'@lsp.typemod.function.defaultLibrary.lua' = '-'
'@lsp.type.property.lua' = '-'
'@lsp.type.method.lua' = '-'

[python]
'@variable.builtin.python' = 'darkyellow'

[Markdown]
'@text.title.1.markdown' = 'red'
'@text.title.2.markdown' = 'red'
'@text.title.3.markdown' = 'red'
'@text.title.4.markdown' = 'red'
'@text.title.5.markdown' = 'red'
'@text.title.6.markdown' = 'red'
'@text.strong.markdown_inline' = 'darkyellow'
'@text.reference.markdown_inline' = 'blue'
'@text.uri.markdown_inline' = 'purple - u'
'@text.title.markdown' = 'fg - b'
'@punctuation.special.markdown' = 'yellow'
'@text.literal.block.markdown' = 'white'
'@text.reference.markdown' = 'blue'
'@lsp.type.class.markdown' = 'blue'
'@text.literal.markdown_inline' = 'darkyellow'
'@text.literal.markdown' = 'darkyellow'
